"""any message

Revision ID: b91c3e0f1309
Revises: d4e7324bf904
Create Date: 2022-09-06 08:02:13.136683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b91c3e0f1309'
down_revision = 'd4e7324bf904'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('course', sa.String(length=100), nullable=True))
    op.add_column('data', sa.Column('batch_num', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data', 'batch_num')
    op.drop_column('data', 'course')
    # ### end Alembic commands ###
